# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

#relative_permalinks: true


# Dependencies
markdown:         kramdown
highlighter:      rouge # changed from `pygments` as github says so
  
# Setup
title:               Chaochen Wang | 王超辰
tagline:             'Be ambitious'
description:         
url:                 winterwang.github.io
baseurl:             ''
paginate:            5
future:              true


# About/contact
author:
  name:              Chaochen Wang
  url:               https://twitter.com/outyousin
  email:             abelardccwang@gmail.com
  github:            winterwang
  google_scholar:    https://scholar.google.co.jp/citations?user=0J-5evgAAAAJ&hl=en
  disqus_shortname:  ccwang
 

## sidebar links:
# For external links add external: true
links:
  - title: <i class="iconside iconm-home"></i> Home
    url: /
  - title: <i class="iconside iconm-user"></i> About
    url: /about/
  - title: <i class="iconside iconm-quill"></i> Blog
    url: /blog/
  - title: <i class="fa fa-tags"></i> Tags
    url: /tags/
  - title: <i class="fa fa-archive"></i> Archive
    url: /archive/
    external: true
  - title: <i class="iconside iconm-envelop"></i> Contact
    url: /contact/
  - title: <i class="iconside iconm-feed2"></i> Feed
    url: /feed.xml



# Custom vars
version:             0.0.0.1
