# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

#relative_permalinks: true

# Setup
title:               Chaochen Wang | 王超辰
tagline:             'Be ambitious'
description:         
url:                 winterwang.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Chaochen Wang
  url:               https://twitter.com/outyousin
  email:             abelardccwang@gmail.com

# Custom vars
version:             0.0.0.1
